In [8]:
# import library
from ase.io import read
import numpy as np

# read QE output file
results_file = 'ontop_fcc111.qe.out'
results = read(results_file, format = 'espresso-out')

# obtain position
positions = results.get_positions()
print( positions )

[[ 0.00000000e+00  0.00000000e+00  1.20000000e+01]
 [ 2.55265548e+00  0.00000000e+00  1.20000000e+01]
 [ 5.10531096e+00  0.00000000e+00  1.20000000e+01]
 [ 7.65796644e+00  0.00000000e+00  1.20000000e+01]
 [ 1.27632774e+00  2.21066449e+00  1.20000000e+01]
 [ 3.82898322e+00  2.21066449e+00  1.20000000e+01]
 [ 6.38163870e+00  2.21066449e+00  1.20000000e+01]
 [ 8.93429418e+00  2.21066449e+00  1.20000000e+01]
 [ 2.55265548e+00  4.42132899e+00  1.20000000e+01]
 [ 5.10531096e+00  4.42132899e+00  1.20000000e+01]
 [ 7.65796644e+00  4.42132899e+00  1.20000000e+01]
 [ 1.02106219e+01  4.42132899e+00  1.20000000e+01]
 [ 3.82898322e+00  6.63199348e+00  1.20000000e+01]
 [ 6.38163870e+00  6.63199348e+00  1.20000000e+01]
 [ 8.93429418e+00  6.63199348e+00  1.20000000e+01]
 [ 1.14869497e+01  6.63199348e+00  1.20000000e+01]
 [ 1.27632774e+00  7.36888164e-01  1.40842345e+01]
 [ 3.82898322e+00  7.36888164e-01  1.40842345e+01]
 [ 6.38163870e+00  7.36888164e-01  1.40842345e+01]
 [ 8.93429418e+00  7.36888164e-

In [9]:
# set the z direction threshold to obtain the atoms of top two layers, including the adsorbate atom
z_threshold = 1.40842345e+01
indices = np.where(positions[:, 2] > z_threshold)[0]

if len(indices) == 0:
    raise ValueError("No atoms found above z_threshold.")


# obtain forces from QE output file
forces_all = results.get_forces()

# obtain the forces of set induces
forces_sel = forces_all[indices]

# calculate the value of force vectors and get the maximum one
max_force = np.max(np.linalg.norm(forces_sel, axis=1))

# print the number of selected atoms
print(f"Selected atoms: {len(indices)}")

# print the maximum force, which should be less than 0.02 eV/Å
print(f"Maximum force = {max_force:.5f} eV/Å")

Selected atoms: 33
Maximum force = 0.00984 eV/Å
